"""
Agent 5 – File Writer
Writes all converted Terraform files to the output directory.
Pure Python – no LLM call.
"""
import os
from pathlib import Path

from src.graph.state import ConversionState


def writer_agent(state: ConversionState) -> ConversionState:
    """
    LangGraph node: persist all converted content to disk.
    Creates the full directory tree as needed.
    """
    output_dir = Path(state.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # ── Write converted resource files ─────────────────────────────────
    for cf in state.converted_files:
        dest = Path(cf.output_path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        try:
            dest.write_text(cf.aws_content, encoding="utf-8")
        except Exception as exc:
            state.errors.append(f"Writer: could not write {dest} – {exc}")

    # ── Write supporting files to root of output dir ───────────────────
    _write_if_content(output_dir / "provider.tf", state.provider_tf)
    _write_if_content(output_dir / "variables.tf", state.variables_tf)
    _write_if_content(output_dir / "outputs.tf", state.outputs_tf)
    _write_if_content(output_dir / "backend.tf", state.backend_tf)

    # ── Write a README.md with migration notes ─────────────────────────
    readme = _build_readme(state)
    _write_if_content(output_dir / "README.md", readme)

    return state


def _write_if_content(path: Path, content: str) -> None:
    if content and content.strip():
        try:
            path.write_text(content, encoding="utf-8")
        except Exception:
            pass  # Errors handled by caller if needed


def _build_readme(state: ConversionState) -> str:
    total_converted = len(state.converted_files)
    total_failed = len(state.failed_files)
    all_aws_resources: list[str] = []
    for f in state.converted_files:
        all_aws_resources.extend(f.resources_converted)
    unique_resources = sorted(set(all_aws_resources))

    lines = [
        "# GCP → AWS Terraform Migration",
        "",
        "Auto-generated by **gcp-to-aws-converter** (LangGraph + LLM)",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Source files processed | {state.total_files} |",
        f"| Files converted | {total_converted} |",
        f"| Files failed | {total_failed} |",
        f"| AWS resource types | {len(unique_resources)} |",
        "",
    ]

    if unique_resources:
        lines += ["## AWS Resources Created", ""]
        for r in unique_resources:
            lines.append(f"- `{r}`")
        lines.append("")

    if state.conversion_plan:
        lines += ["## Conversion Plan", "", state.conversion_plan, ""]

    if state.warnings:
        lines += ["## ⚠️ Warnings", ""]
        for w in state.warnings:
            lines.append(f"- {w}")
        lines.append("")

    if state.failed_files:
        lines += ["## ❌ Failed Files", ""]
        for f in state.failed_files:
            lines.append(f"- {f}")
        lines.append("")

    lines += [
        "## Next Steps",
        "",
        "1. Review and update `variables.tf` with your actual values.",
        "2. Configure `backend.tf` for remote state (recommended).",
        "3. Run `terraform init` to initialise providers.",
        "4. Run `terraform plan` to review the execution plan.",
        "5. Run `terraform apply` to provision the AWS infrastructure.",
        "",
        "> **Note**: Always review the generated code before applying to production.",
        "  IAM policies in particular should be reviewed for least-privilege compliance.",
        "",
    ]

    return "\n".join(lines)
